# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-de
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 9092
      targetPort: 9092
